ui_font_families = ["Aa顺風顺水顺财神"]
asr_backend = "sense-voice"
model = "/home/cyrus/Downloads/auto-voice/models/sense-voice/model.int8.onnx"
tokens = "/home/cyrus/Downloads/auto-voice/models/sense-voice/tokens.txt"
speaker_segmentation_model = "models/speaker-diarization/sherpa-onnx-pyannote-segmentation-3-0/model.int8.onnx"
speaker_embedding_model = "models/speaker-diarization/3dspeaker/3dspeaker_speech_eres2net_large_sv_zh-cn_3dspeaker_16k.onnx"
lm_url = "http://localhost:12345"
lang = "en"
lm_model = "qwen/qwen3.5-9b"
no_llm = true
lmstudio_auto_start = true
lmstudio_model = "qwen/qwen3.5-9b"
lmstudio_context_length = 4096
energy_threshold = 0.009999999776482582
vad_silence_ms = 800
ptt_key = "RightAlt"
hr_lexicon = "models/hr/lexicon.txt"
hr_rule_fsts = "models/hr/replace.fst"
